# Generated by Django 2.2 on 2023-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_auto_20220529_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextKeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.CharField(max_length=30)),
                ('value', models.TextField()),
            ],
        ),
    ]
