version: '3'
services:
  uploadnginx:
    image: nginx:latest
    container_name: nginxwithupload
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ..:/src
      - /home/ywz/1:/src/files/1 #you can change this ori path, be consistent with next one
      - /home/ywz/secret:/src/files/secret
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - uploadweb
  uploadweb:
    build: .
    image: backend_upload_image
    container_name: djangoback
    # command: ./dev_start.sh #bash -c "python django1/manage.py runserver 0.0.0.0:8000 > django.log 2>&1"
    command: bash -c "uwsgi --ini django1/uwsgi.ini && tail -f /dev/null"
    volumes:
      - ..:/src
      - /home/ywz/1:/src/files/1 #you can change this ori path, be consistent with last one
      - /home/ywz/secret:/src/files/secret
    expose:
      - "8000"
    restart: always
